Task/add string html extensions
sequenia/SQDevKit pull request #1
Opened 2021-03-25 07:06 UTC by cefiro666

Добавил новые расширения

2021-03-26 04:19 UTC, Simeon123 requested changes
Накидал немного комментов)

2021-03-26 04:19 UTC, Simeon123 commented on Sources/Extensions/Foundation/NSAttributedMutableString/NSAttributedMutableString+SQDevKit.swift
> +public extension SQDevKit where Base: NSMutableAttributedString {
А сделай такое же расширение для обычных аттрибутных строк, такое, чтоб каждая функция возвращала Self
Чтобы можно было группой эти методы вызвать:
```swift
NSAttributedString(string, attributes: [.font: someCoolFont])
    .setColor(forText: "Paint it black!", withColor: .black)
    .setFont(forText: "Other font", withColor: someOtherCoolFont)
```
И я б еще для underscore отдельный сделал еще, достаточно популярная необходимость

2021-03-26 04:19 UTC, Simeon123 commented on Sources/Extensions/Foundation/NSAttributedMutableString/NSAttributedMutableString+SQDevKit.swift
> +    func setColorForText(textForAttribute: String, withColor color: UIColor) {
Запили это немного в другом именном формате, так покрасивше по моему пишется:
```swift
func setColor(forText textForAttribute: String, withColor color: UIColor)
```

2021-03-26 04:19 UTC, Simeon123 commented on Sources/Extensions/Foundation/NSAttributedMutableString/NSAttributedMutableString+SQDevKit.swift
> +    func setFontForText(textForAttribute: String, withFont font: UIFont) {
Ну и тут в таком же ключе:
Запили это немного в другом именном формате, так покрасивше по моему пишется:
```swift
func setFont(forText textForAttribute: String, withFont color: UIFont)
```

2021-03-26 04:19 UTC, Simeon123 commented on Sources/Extensions/Foundation/String/String+SQDevKit.swift
> +    func htmlAttributed(using font: UIFont, color: UIColor) -> NSAttributedString? {
Using на with замени лучше наверное, красивше звучит, видать скопипиздил откуда то, так и осталось

2021-03-26 04:19 UTC, Simeon123 commented on Sources/Extensions/Foundation/String/String+SQDevKit.swift
> +    func toDateFromISOString() -> Date? {
А переквалифицируй это дело в переменную и назови просто toDate. И в комменте пропиши, что строка должна быть ISO-форматом с примером, как выглядит ISO-формат

2021-03-26 04:19 UTC, Simeon123 commented on Sources/Extensions/Foundation/Bundle/Bundle+SQDevKit.swift
> +    var releaseVersionNumber: String? {
У меня ж были уже эти функции вроде, нет?

2021-03-26 04:19 UTC, Simeon123 commented on Sources/Extensions/Foundation/Date/Date+SQDevKit.swift
> +    func setTime(hour: Int?, minute: Int?) -> Date? {
А может лучше их не опционалами, а со значением .zero по дефолту?

2021-03-26 04:19 UTC, Simeon123 commented on Sources/Extensions/Foundation/Date/Date+SQDevKit.swift
> +    func dayNumberOfWeek() -> Int? {
Это тоже можно переквалифицировать в переменную

2021-03-26 04:33 UTC, Simeon123 commented on Sources/Extensions/Foundation/NSAttributedMutableString/NSAttributedMutableString+SQDevKit.swift
> +public extension SQDevKit where Base: NSMutableAttributedString {
А, и обоих двоих их сделай как `@discardableResult`. Мне начинает эта схема нравиться, лаконично пишется достаточно при такой конфигруации по кусочкам

2021-03-26 04:44 UTC, cefiro666 commented on Sources/Extensions/Foundation/Bundle/Bundle+SQDevKit.swift
> +    var releaseVersionNumber: String? {
Точно, есть. Удалил.

2021-03-26 04:44 UTC, cefiro666 commented on Sources/Extensions/Foundation/Date/Date+SQDevKit.swift
> +    func setTime(hour: Int?, minute: Int?) -> Date? {
Поправил.

2021-03-26 04:46 UTC, cefiro666 commented on Sources/Extensions/Foundation/Date/Date+SQDevKit.swift
> +    func dayNumberOfWeek() -> Int? {
Поправил.

2021-03-26 04:47 UTC, cefiro666 commented on Sources/Extensions/Foundation/NSAttributedMutableString/NSAttributedMutableString+SQDevKit.swift
> +    func setColorForText(textForAttribute: String, withColor color: UIColor) {
Поправил.

2021-03-26 04:47 UTC, cefiro666 commented on Sources/Extensions/Foundation/NSAttributedMutableString/NSAttributedMutableString+SQDevKit.swift
> +    func setFontForText(textForAttribute: String, withFont font: UIFont) {
Поправил.

2021-03-26 04:48 UTC, Simeon123 requested changes
Накидал немного комментов)

2021-03-26 04:48 UTC, Simeon123 commented on Sources/Extensions/Foundation/Date/Date+SQDevKit.swift
> +    func toString(format: String, locale: String = "ru_RU") -> String {
А, переобзови еще тут не locale, а langCode
И можно добавить к ней в пару функцию, которая как раз объект Locale принимать на вход

2021-03-26 04:51 UTC, cefiro666 commented on Sources/Extensions/Foundation/String/String+SQDevKit.swift
> +    func toDateFromISOString() -> Date? {
Поправил.

2021-03-26 04:51 UTC, cefiro666 commented on Sources/Extensions/Foundation/String/String+SQDevKit.swift
> +    func htmlAttributed(using font: UIFont, color: UIColor) -> NSAttributedString? {
Поправил.

2021-03-26 05:15 UTC, cefiro666 commented on Sources/Extensions/Foundation/NSAttributedMutableString/NSAttributedMutableString+SQDevKit.swift
> +public extension SQDevKit where Base: NSMutableAttributedString {
Добавил)

2021-03-26 05:22 UTC, cefiro666 commented on Sources/Extensions/Foundation/Date/Date+SQDevKit.swift
> +    func toString(format: String, locale: String = "ru_RU") -> String {
Поправил

2021-03-26 05:22 UTC, cefiro666 commented on Sources/Extensions/Foundation/NSAttributedMutableString/NSAttributedMutableString+SQDevKit.swift
> +public extension SQDevKit where Base: NSMutableAttributedString {
Поправил

2021-03-26 08:06 UTC, Simeon123 requested changes
Добавил еще чуть чуть

2021-03-26 08:06 UTC, semen-sequenia commented on Sources/Extensions/Foundation/Date/Date+SQDevKit.swift
> +    ///   - locale: locale for format.`String`.
Коммент то обнови)

2021-03-26 08:06 UTC, semen-sequenia commented on Sources/Extensions/Foundation/NSAttributedString/NSAttributedString+SQDevKit.swift
> +        return NSAttributedString(attributedString: mutableString)
А в этих местах нельзя использовать уже написанные методы от мутабельных аттрибутных строк? (или наоборот) чтоб дубликатов не устраивать

2021-03-29 06:54 UTC, cefiro666 commented on Sources/Extensions/Foundation/Date/Date+SQDevKit.swift
> +    ///   - locale: locale for format.`String`.
Поправил

2021-03-29 06:54 UTC, cefiro666 commented on Sources/Extensions/Foundation/NSAttributedString/NSAttributedString+SQDevKit.swift
> +        return NSAttributedString(attributedString: mutableString)
Поправил

2021-03-29 16:28 UTC, merged